parameters:
    allowed_email_domain: '%env(default::ALLOWED_EMAIL_DOMAIN)%'
    jwt_ttl: '%env(int:JWT_TTL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\JwtCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJwtCreated }

    App\EventListener\SecurityHeadersListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
